apk:
  stage: build
  image: "cirrusci/flutter:stable"
  script:
    - flutter build apk
  after_script:
    - mv $CI_PROJECT_DIR/build/app/outputs/apk/release/app-release.apk $CI_PROJECT_DIR/lernapp.apk
  artifacts:
    name: android
    paths:
      - $CI_PROJECT_DIR/lernapp.apk

web:
  stage: build
  image: "cirrusci/flutter:stable"
  script:
    - flutter build web --dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/ # Self host canvaskit
    - tar -cvf web.tar -C ./build/ web
  artifacts:
    name: web
    paths:
      - $CI_PROJECT_DIR/web.tar

test:
  stage: test
  image: "cirrusci/flutter:stable"
  script: flutter test test/unit_tests

stages:
  - test
  - build