before_script:
  - echo $CI_COMMIT_REF_NAME > version
  - echo $CI_COMMIT_SHORT_SHA >> version

test:
  stage: test
  image: "cirrusci/flutter:stable"
  script:
    - flutter test test/unit_tests


web:
  stage: build
  image: "cirrusci/flutter:stable"
  dependencies:
    - test
  script:
    - flutter build web --dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/ # Self host canvaskit
    - tar -cvf web.tar -C ./build/ web
  artifacts:
    name: web
    paths:
      - $CI_PROJECT_DIR/web.tar

apk:
  stage: build
  image: "cirrusci/flutter:stable"
  dependencies:
    - test
  script:
    - flutter build apk
  after_script:
    - mv $CI_PROJECT_DIR/build/app/outputs/apk/release/app-release.apk $CI_PROJECT_DIR/lernapp.apk
  artifacts:
    name: android
    paths:
      - $CI_PROJECT_DIR/lernapp.apk


deploy:
  stage: deploy
  dependencies:
    - web
  only:
    - master
  image: "cirrusci/flutter:stable"
  script:
    # Ssh refuses to read keyfiles which are globally readable
    - chmod 600 $DeployKey
    - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    # Ssh won't connect to unknown keys in non-interactive mode, this figures out the server's keys
    - ssh-keyscan $DeployTargetServer >> ~/.ssh/known_hosts
    - tar -xvf $CI_PROJECT_DIR/web.tar
    - ssh -i $DeployKey $DeployUser@$DeployTargetServer "rm -r /var/www/html/lernapp"
    - scp -i $DeployKey -r web $DeployUser@$DeployTargetServer:/var/www/html/lernapp
  after_script:
    - rm -r web

stages:
  - test
  - build
  - deploy
